services:
  IMAI-LAB:           
    image: ${T_UP}         
    stdin_open: true       # -i 옵션
    tty: true              # -t 옵션
    ipc: host              # --ipc=host 옵션
    runtime: nvidia        # --runtime=nvidia 옵션
    working_dir: /usr_creative  # -w /usr_creative 옵션
    volumes:
      - ./:/usr_creative   

    # --gpus all 옵션 (최신 표준 방식)
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
